In [1]:
a=[1,2,3,4,5]
type(a)

list

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [4]:
arr1=np.array((1,2,3,4,5))
print(arr1)

[1 2 3 4 5]


In [6]:
arr2=np.array(arr1,float)
print(arr2)

[1. 2. 3. 4. 5.]


In [8]:
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [10]:
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)
arr3.size

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


12

In [11]:
arr3.shape

(2, 2, 3)

In [13]:
arr3.ndim

3

In [18]:
arr4=np.array([1,2,3,4,5], ndmin=5)
print(arr4)

[[[[[1 2 3 4 5]]]]]


In [19]:
arr=np.array([1,2,3,4,5])
arr[1]

2

In [20]:
arr[2]+arr[2]

6

In [25]:
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3[1,2])
print(arr3[0,2])
print(arr3[1,0])

[[1 2 3]
 [4 5 6]]
6
3
4


In [27]:
arr3=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]]])
print(arr3)
print(arr3[1,1,1])
print(arr3[0,1,2])
print(arr3[1,1,2])
print(arr3[2,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]
15
6
16
25


In [31]:
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3[1,-1])
print(arr3[1,-2])
print(arr3[1,-3])
print(arr3[0,-1])
print(arr3[0,-2])
print(arr3[0,-3])

[[1 2 3]
 [4 5 6]]
6
5
4
3
2
1


In [32]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr[1:3])
print(arr[:4])
print(arr[1:])

[1 2 3 4 5]
[2 3]
[1 2 3 4]
[2 3 4 5]


In [33]:
print(arr.dtype)

int32


In [34]:
arr=np.array([1.1,2.2,3.3,4.4,5.5])
print(arr.dtype)

float64


In [36]:
arr=np.array(['a','b','c','d'])
print(arr.dtype)
arr1=np.array(['ab','bn','cn','dn'])
print(arr1.dtype)

<U1
<U2


In [39]:
arr=np.array([1,2,3])
print(np.array(arr,complex))
print(np.array(arr,float))

[1.+0.j 2.+0.j 3.+0.j]
[1. 2. 3.]


In [9]:
arr=np.array([1,2,3,0,0.5,-2])
print(np.array(arr,bool))

[ True  True  True False  True  True]


In [10]:
x=np.arange(2,10)
print(x)
print(type(x))

[2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [21]:
a=np.array([1,2,3,4,5,6,7,8])
a1=a.reshape(2,2,-1)
print(a1)
a=np.array([1,2,3,4,5,6,7,8])
a1=a.reshape(2,2,2)
print(a1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
a=np.array([[[1,2,3,4]],[[5,6,7,8]]])
a1=a.reshape(-1)
print(a1)
a=np.array([[[1,2,3,4]],[[5,6,7,8]]])
a1=a.reshape(-2)
print(a1)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [5]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [4]:
a=np.array([[1,2,3,4],[5,6,7,8]])
for x in a:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [11]:
a=np.array([1,2,3,4,5,6]).reshape(2,3)
print(a)
a=np.array([1,2,3,4,5,6]).reshape(3,2)
print(a)
b=np.array([11,12,13,14,15,16]).reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[11 12 13]
 [14 15 16]]


In [19]:
a=np.array([1,2,3,4,5,6]).reshape(2,3)
b=np.array([11,12,13,14,15,16]).reshape(2,3)
c=np.concatenate((a,b))
print(c)
c=np.concatenate((a,b),axis=1)
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


In [21]:
c=np.stack((a,b),axis=0)
print(c)
c=np.stack((a,b),axis=1)
print(c)
c=np.stack((a,b))
print(c)
c=np.hstack((a,b))
print(c)
c=np.vstack((a,b))
print(c)


[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
[[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [14 15 16]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]
[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


In [22]:
a=np.array([1,2,3,4,5,6])
b=np.append(a,[7,8,9])
print(b)

[1 2 3 4 5 6 7 8 9]


In [23]:
a=np.array([1,2,3,4,5,6])
b=np.insert(a,3,[0,0,0])
print(b)

[1 2 3 0 0 0 4 5 6]


In [25]:
a=np.array([1,2,3,4,5,6])
b=np.delete(a,4)
print(b)
b=np.delete(a,1)
print(b)

[1 2 3 4 6]
[1 3 4 5 6]


In [31]:
arr=np.empty(5)
print(arr)

[2.12199579e-314 1.39839523e-311 4.48611606e-321 8.28942550e-317
 1.39893004e-311]


In [30]:
arr=np.empty((3,3))
print(arr)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [3.56028794e-307 1.16820537e-307 1.42419938e-306]
 [7.56603881e-307 8.45603440e-307 3.49698923e-317]]


In [29]:
arr=np.empty((3,3),dtype=int)
print(arr)

[[1 2 3]
 [0 0 0]
 [4 5 6]]


In [32]:
arr=np.zeros((3,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [33]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:
arr=np.eye((3),dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [36]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [37]:
arr=np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [39]:
a=np.linspace(11,20,2)
print(a)
a=np.linspace(11,20,3)
print(a)
a=np.linspace(11,20,10)
print(a)
a=np.linspace(11,20,15)
print(a)

[11. 20.]
[11.  15.5 20. ]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
[11.         11.64285714 12.28571429 12.92857143 13.57142857 14.21428571
 14.85714286 15.5        16.14285714 16.78571429 17.42857143 18.07142857
 18.71428571 19.35714286 20.        ]


In [40]:
a=np.linspace(1,10,100)
print(a)
a=np.linspace(1,100,10)
print(a)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [41]:
a=np.random.rand(10)
print(a)

[0.7823744  0.17610499 0.25625394 0.24266999 0.68113818 0.76160711
 0.27175941 0.24559125 0.27055761 0.24948511]


In [42]:
a=np.random.rand(3,3)
print(a)

[[0.07608014 0.13018052 0.2564043 ]
 [0.12788498 0.22330933 0.38361295]
 [0.59086992 0.24544849 0.31825729]]


In [43]:
a=np.random.randn(3,3)
print(a)

[[-0.00960389 -0.91410211  1.61724651]
 [ 1.76652884 -0.30924536  0.36564272]
 [-1.33615109 -0.63170591 -1.41172669]]


In [44]:
x=list(range(1,11))
print(x)
print(x*2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [47]:
a=np.arange(1,11)
print(a)
print(a*2)
print(a+100)
print(a-2)
print(a/10)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[101 102 103 104 105 106 107 108 109 110]
[-1  0  1  2  3  4  5  6  7  8]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [48]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(a>4)
print(a%2==0)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False  True  True  True  True  True  True]
[False  True False  True False  True False  True False  True]


In [51]:
mask=a%2==0
print(mask)
print(a[mask])

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


In [58]:
names=np.array(["pooja","mrunal","pooja","pooja","pooja","mrunal","shubhangi"])
mask=names=="pooja"
print(mask)
print(names[mask])

[ True False  True  True  True False False]
['pooja' 'pooja' 'pooja' 'pooja']


In [60]:
print(names[names=="pooja"])
print(names[names!="pooja"])

['pooja' 'pooja' 'pooja' 'pooja']
['mrunal' 'mrunal' 'shubhangi']


In [62]:
a=(names!="pooja")
b=(names!="mrunal")
print(a&b)
print(a|b)

[False False False False False False  True]
[ True  True  True  True  True  True  True]


In [63]:
c=names[a&b]
print(c)

['shubhangi']


In [4]:
import numpy as np
names=np.array(["pooja","mrunal","pooja","pooja","pooja","mrunal","shubhangi"])
c=names[(names!="pooja")&(names!="mrunal")]
print(c)

['shubhangi']


In [5]:
a=np.array([[1,2,3],[4,5,0],[2,1,1]])
b=np.array([[1,2,3],[1,3,1],[4,0,2]])
print(a)
print(b)

[[1 2 3]
 [4 5 0]
 [2 1 1]]
[[1 2 3]
 [1 3 1]
 [4 0 2]]


In [9]:
add=np.add(a,b)
print(add)
print(a+b)

[[2 4 6]
 [5 8 1]
 [6 1 3]]
[[2 4 6]
 [5 8 1]
 [6 1 3]]


In [10]:
subtract=np.subtract(a,b)
print(subtract)
print(a-b)

[[ 0  0  0]
 [ 3  2 -1]
 [-2  1 -1]]
[[ 0  0  0]
 [ 3  2 -1]
 [-2  1 -1]]


In [12]:
mul=np.multiply(a,b)
c=np.dot(a,b)
print(c)
print(mul)
print(a*b)

[[15  8 11]
 [ 9 23 17]
 [ 7  7  9]]
[[ 1  4  9]
 [ 4 15  0]
 [ 8  0  2]]
[[ 1  4  9]
 [ 4 15  0]
 [ 8  0  2]]


In [13]:
div=np.divide(a,b)
print(div)
print(a/b)

[[1.         1.         1.        ]
 [4.         1.66666667 0.        ]
 [0.5               inf 0.5       ]]
[[1.         1.         1.        ]
 [4.         1.66666667 0.        ]
 [0.5               inf 0.5       ]]


C:\Users\C2PC-15\AppData\Local\Temp\ipykernel_9420\1669067292.py:1: RuntimeWarning: divide by zero encountered in divide
  div=np.divide(a,b)
C:\Users\C2PC-15\AppData\Local\Temp\ipykernel_9420\1669067292.py:3: RuntimeWarning: divide by zero encountered in divide
  print(a/b)


In [14]:
rem=np.remainder(a,b)
print(rem)

[[0 0 0]
 [0 2 0]
 [2 0 1]]


C:\Users\C2PC-15\AppData\Local\Temp\ipykernel_9420\2364390991.py:1: RuntimeWarning: divide by zero encountered in remainder
  rem=np.remainder(a,b)


In [20]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(a*b)
print(np.dot(a,b))

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [21]:
c=np.matmul(a,b)
print(c)

[[ 7 10]
 [15 22]]


In [22]:
n=np.kron([1,2,3],[5,2,3])
print(n)

[ 5  2  3 10  4  6 15  6  9]


In [24]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
n=np.kron(a,b)
print(n)

[[ 1  2  2  4]
 [ 3  4  6  8]
 [ 3  6  4  8]
 [ 9 12 12 16]]


In [26]:
arr=np.array([0,1,2,3,4,5])
print(arr)
print(arr*10)
num=np.sqrt(arr)
print(num)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0.         1.         1.41421356 1.73205081 2.         2.23606798]


In [27]:
print(np.ceil(num))
print(np.floor(num))

[0. 1. 2. 2. 2. 3.]
[0. 1. 1. 1. 2. 2.]


In [32]:
print(arr.mean())
print(arr.std())
print(arr.max())
print(arr.min())
print(arr.argmax())
print(arr.argmin())
print(arr.sum())
print(arr.sum(axis=0))


2.5
1.707825127659933
5
0
5
0
15
15


In [33]:
a=np.array([[1,2],[3,4]])
print(a.flatten())

[1 2 3 4]


In [34]:
a=np.arange(1,11)
print(a)
print(a[3:6])

[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6]


In [38]:
b=a[3:6]
print(b)
b[:]=100
print(b)
print(a)


[100 100 100]
[100 100 100]
[  1   2   3 100 100 100   7   8   9  10]


In [39]:
b=a[3:6].copy()
print(b)
b[:]=0
print(b)
print(a)

[100 100 100]
[0 0 0]
[  1   2   3 100 100 100   7   8   9  10]
